### ISSUE TITLE
Dead Discord link

### ISSUE THREAD

**Issue by phoe** [iledopapiezowej/iledopapiezowej#33]
https://github.com/iledopapiezowej/iledopapiezowej/blob/8696f50e59771816958aa41ce10c593c41769c11/src/components/Settings/Settings.tsx#L173

https://github.com/iledopapiezowej/iledopapiezowej/blob/1587e332ed086945fc81005e3ba0f662b80c4893/public/promo.json#L4

This invitation has expired.

**Comment by Maathias** [comment]
fixed long time ago
