### ISSUE TITLE
bug/Login-via-discord

### ISSUE THREAD

**Issue by miki164** [iledopapiezowej/iledopapiezowej#42]
**Description of the bug**
The button to log in doesn't work.

**Steps to reproduce**
1. Open "ustawienia" > "konto"
2. Click "Zaloguj przez discord"

**Image (optional)**
![image](https://user-images.githubusercontent.com/32245772/229357720-936be1a5-41b7-4def-a8c1-f70f5a9670eb.png)

**Comment by Maathias** [comment]
AFAIK this is an experimental feature. It should not be on a production build
